language: ruby
bundler_args: --without development integration
rvm:
  - 2.0
  - 2.1
  - 2.2
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
